apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-devops
  labels:
    app.kubernetes.io/name: kube-devops
rules:
  - apiGroups: ["devops.stochastic.io"]
    resources: ["devopspolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["devops.stochastic.io"]
    resources: ["devopspolicies/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update"]
