apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-devops-watch
  namespace: kube-devops
  labels:
    app.kubernetes.io/name: kube-devops
    app.kubernetes.io/component: watch
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-devops
      app.kubernetes.io/component: watch
