apiVersion: v1
kind: Service
metadata:
  name: kube-devops-reconcile
  namespace: kube-devops
  labels:
    app.kubernetes.io/name: kube-devops
    app.kubernetes.io/component: reconcile
spec:
  selector:
    app.kubernetes.io/name: kube-devops
    app.kubernetes.io/component: reconcile
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
