apiVersion: v1
kind: Service
metadata:
  name: kube-devops-webhook
  namespace: kube-devops
  labels:
    app.kubernetes.io/name: kube-devops
    app.kubernetes.io/component: webhook
spec:
  selector:
    app.kubernetes.io/name: kube-devops
    app.kubernetes.io/component: webhook
  ports:
    - name: metrics
      port: 8443
      targetPort: 8443
      protocol: TCP
