apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-devops-webhook
  namespace: kube-devops
  labels:
    app.kubernetes.io/name: kube-devops
    app.kubernetes.io/component: webhook
    release: stable
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-devops
      app.kubernetes.io/component: webhook
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
